<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagementSystem.TestCommon\TaskManagementSystem.TestCommon.csproj" />
    <ProjectReference Include="..\..\src\Database\TaskManagementSystem.Database\TaskManagementSystem.Database.csproj" />
  </ItemGroup>
</Project>
