<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagementSystem.TestCommon\TaskManagementSystem.TestCommon.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\TaskManagementSystem.BuildingBlocks.Persistence\TaskManagementSystem.BuildingBlocks.Persistence.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\TaskManagementSystem.IntegrationEvents\TaskManagementSystem.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\src\Database\TaskManagementSystem.Database\TaskManagementSystem.Database.csproj" />
  </ItemGroup>
</Project>
