<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TaskManagementSystem.TestCommon\TaskManagementSystem.TestCommon.csproj" />
    <ProjectReference Include="..\..\src\Modules\Organization\TaskManagementSystem.Modules.Organization\TaskManagementSystem.Modules.Organization.csproj" />
  </ItemGroup>
</Project>
