#!/usr/bin/env bash
# Per-boot startup for the ATS / TaskManagementSystem dev environment.
# Brings up SQL Server (no systemd in the container, so sqlservr is launched
# directly), waits for readiness, provisions/migrates the modular DB, and writes
# a shared env file that the app terminals source. Idempotent across restarts.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export PATH="$PATH:/usr/local/bin:/opt/mssql-tools18/bin"

# Local-dev-only SA credential. Override by setting the MSSQL_SA_PASSWORD secret;
# this default is used only for the throwaway SQL Server inside the isolated VM.
SA_PASSWORD="${MSSQL_SA_PASSWORD:-Dev#Str0ng2026}"
TMS_DB="TaskManagementSystem"
LEGACY_DB="SystemAdminDB_Test_v1"

log() { echo "[start] $*"; }

# --- Launch SQL Server (persist across the start script exiting) -----------
if ! pgrep -x sqlservr >/dev/null 2>&1; then
  log "Starting SQL Server..."
  sudo mkdir -p /var/log/mssql && sudo chown mssql:mssql /var/log/mssql || true
  sudo -u mssql env ACCEPT_EULA=Y MSSQL_PID=Developer MSSQL_SA_PASSWORD="$SA_PASSWORD" \
    nohup /opt/mssql/bin/sqlservr >/tmp/sqlservr.log 2>&1 &
  disown || true
else
  log "SQL Server already running."
fi

# --- Wait for readiness ----------------------------------------------------
log "Waiting for SQL Server to accept connections..."
for i in $(seq 1 60); do
  if /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C \
       -Q "SELECT 1" >/dev/null 2>&1; then
    log "SQL Server is ready."
    break
  fi
  sleep 2
  if [ "$i" -eq 60 ]; then
    log "ERROR: SQL Server did not become ready in time."
    tail -20 /tmp/sqlservr.log || true
    exit 1
  fi
done

# --- Provision + migrate the modular TaskManagementSystem database ---------
DB_DIR="$REPO_ROOT/TaskManagementSystem"
CONN="Server=localhost;Database=$TMS_DB;User Id=sa;Password=$SA_PASSWORD;TrustServerCertificate=True"

log "Ensuring database '$TMS_DB' exists..."
/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$SA_PASSWORD" -C \
  -i "$DB_DIR/src/Database/TaskManagementSystem.Database/Scripts/CreateDatabase.sql"

log "Running DbUp migrations..."
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1
( cd "$DB_DIR" && dotnet run --project src/Database/DatabaseMigrator --no-build -- \
    "$CONN" "src/Database/TaskManagementSystem.Database/Scripts/Migrations" )

# --- Publish connection strings for the app terminals ----------------------
ENV_FILE="$HOME/.tms-dev-env.sh"
cat > "$ENV_FILE" <<EOF
# Generated by .cursor/start.sh — sourced by the app terminals.
export PATH="\$PATH:/usr/local/bin:/opt/mssql-tools18/bin"
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1
export ASPNETCORE_ENVIRONMENT=Development
export TMS_CONNECTION="Server=localhost;Database=$TMS_DB;User Id=sa;Password=$SA_PASSWORD;TrustServerCertificate=True"
export LEGACY_CONNECTION="Server=localhost;Database=$LEGACY_DB;User Id=sa;Password=$SA_PASSWORD;TrustServerCertificate=True"
EOF

log "Startup complete. Connection strings written to $ENV_FILE."
