// <auto-generated />
using System;
using AutomatedTaskSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomatedTaskSystem.Migrations
{
	[DbContext(typeof(DataContext))]
	[Migration("20220512105211_Seed4")]
	partial class Seed4
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.4")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("AppUserProject", b =>
				{
					b.Property<int>("ProjectsId")
						.HasColumnType("int");

					b.Property<string>("UsersId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("ProjectsId", "UsersId");

					b.HasIndex("UsersId");

					b.ToTable("AppUserProject");
				});

			modelBuilder.Entity("AppUserTeam", b =>
				{
					b.Property<int>("TeamsId")
						.HasColumnType("int");

					b.Property<string>("UsersId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("TeamsId", "UsersId");

					b.HasIndex("UsersId");

					b.ToTable("AppUserTeam");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.AppUser", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<int>("AccessFailedCount")
						.HasColumnType("int");

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Email")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<bool>("EmailConfirmed")
						.HasColumnType("bit");

					b.Property<string>("FirstName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GroupId")
						.HasColumnType("int");

					b.Property<string>("LastName")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("LockoutEnabled")
						.HasColumnType("bit");

					b.Property<DateTimeOffset?>("LockoutEnd")
						.HasColumnType("datetimeoffset");

					b.Property<string>("NormalizedEmail")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedUserName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("PasswordHash")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("PhoneNumber")
						.HasColumnType("nvarchar(max)");

					b.Property<bool>("PhoneNumberConfirmed")
						.HasColumnType("bit");

					b.Property<string>("SecurityStamp")
						.HasColumnType("nvarchar(max)");

					b.Property<int>("TitleId")
						.HasColumnType("int");

					b.Property<bool>("TwoFactorEnabled")
						.HasColumnType("bit");

					b.Property<string>("UserName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("GroupId");

					b.HasIndex("NormalizedEmail")
						.HasDatabaseName("EmailIndex");

					b.HasIndex("NormalizedUserName")
						.IsUnique()
						.HasDatabaseName("UserNameIndex")
						.HasFilter("[NormalizedUserName] IS NOT NULL");

					b.HasIndex("TitleId");

					b.ToTable("AspNetUsers", (string)null);
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Group", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Groups");

					b.HasData(
						new
						{
							Id = 1,
							Archived = false,
							Description = "Identity Designer",
							Name = "ID"
						},
						new
						{
							Id = 2,
							Archived = false,
							Description = "Subject Matter Executive",
							Name = "SME"
						},
						new
						{
							Id = 3,
							Archived = false,
							Description = "Project Manager",
							Name = "PM"
						},
						new
						{
							Id = 4,
							Archived = false,
							Description = "Proofreader",
							Name = "PR"
						},
						new
						{
							Id = 5,
							Archived = false,
							Description = "Voice Over",
							Name = "VO"
						},
						new
						{
							Id = 6,
							Archived = false,
							Description = "Graphic Designer",
							Name = "GD"
						});
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.LearningObjective", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Lesson")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("ProjectId")
						.HasColumnType("int");

					b.Property<int>("TypeId")
						.HasColumnType("int");

					b.Property<int>("Unit")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("ProjectId");

					b.HasIndex("TypeId");

					b.ToTable("LearningObjectives");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.LearningObjectiveType", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("LearningObjectivesTypes");

					b.HasData(
						new
						{
							Id = 1,
							Archived = false,
							Description = "An interactive application with learning objective.",
							Name = "Interactive"
						},
						new
						{
							Id = 2,
							Archived = false,
							Description = "A Live Video that explains the learning objective.",
							Name = "Live Video"
						},
						new
						{
							Id = 3,
							Archived = false,
							Description = "A gamified learning objective.",
							Name = "Game"
						});
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Project", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Projects");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Schema", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("Duration")
						.HasColumnType("int");

					b.Property<int>("GroupId")
						.HasColumnType("int");

					b.Property<bool>("IsStart")
						.HasColumnType("bit");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int?>("Next")
						.HasColumnType("int");

					b.Property<int>("Serial")
						.HasColumnType("int");

					b.Property<int>("TypeId")
						.HasColumnType("int");

					b.HasKey("Id");

					b.HasIndex("GroupId");

					b.HasIndex("TypeId");

					b.ToTable("Schemas");

					b.HasData(
						new
						{
							Id = 1,
							Archived = false,
							Description = "ID writing the storyboard",
							Duration = 3600,
							GroupId = 1,
							IsStart = true,
							Name = "Storyboard writing",
							Next = 2,
							Serial = 1,
							TypeId = 1
						},
						new
						{
							Id = 2,
							Archived = false,
							Description = "SME review the storyboard that the ID wrote",
							Duration = 3600,
							GroupId = 2,
							IsStart = false,
							Name = "Storyboard Review",
							Next = 3,
							Serial = 2,
							TypeId = 1
						},
						new
						{
							Id = 3,
							Archived = false,
							Description = "Design Proof Analysis",
							Duration = 3600,
							GroupId = 4,
							IsStart = false,
							Name = "Analysis",
							Next = 4,
							Serial = 3,
							TypeId = 1
						},
						new
						{
							Id = 4,
							Archived = false,
							Description = "Recording Voice Over",
							Duration = 3600,
							GroupId = 5,
							IsStart = false,
							Name = "Voice Over",
							Next = 5,
							Serial = 4,
							TypeId = 1
						},
						new
						{
							Id = 5,
							Archived = false,
							Description = "Graphic Design",
							Duration = 3600,
							GroupId = 6,
							IsStart = false,
							Name = "Graphics",
							Next = 6,
							Serial = 4,
							TypeId = 1
						},
						new
						{
							Id = 6,
							Archived = false,
							Description = "Voice Over Review",
							Duration = 3600,
							GroupId = 4,
							IsStart = false,
							Name = "Review",
							Serial = 5,
							TypeId = 1
						},
						new
						{
							Id = 7,
							Archived = false,
							Description = "Graphic Design Review",
							Duration = 3600,
							GroupId = 1,
							IsStart = false,
							Name = "Review",
							Serial = 6,
							TypeId = 1
						});
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Task", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<int>("GroupId")
						.HasColumnType("int");

					b.Property<bool>("IsRollback")
						.HasColumnType("bit");

					b.Property<int>("LearningObjectiveId")
						.HasColumnType("int");

					b.Property<int?>("ParentId")
						.HasColumnType("int");

					b.Property<int>("ProjectId")
						.HasColumnType("int");

					b.Property<int>("SchemaId")
						.HasColumnType("int");

					b.Property<int>("StatusId")
						.HasColumnType("int");

					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<DateTime>("due")
						.HasColumnType("datetime2");

					b.HasKey("Id");

					b.HasIndex("GroupId");

					b.HasIndex("LearningObjectiveId");

					b.HasIndex("ParentId");

					b.HasIndex("ProjectId");

					b.HasIndex("SchemaId");

					b.HasIndex("StatusId");

					b.HasIndex("UserId");

					b.ToTable("Tasks");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.TaskStatus", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("TaskStatus");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Team", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<int>("GroupId")
						.HasColumnType("int");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.HasIndex("GroupId");

					b.ToTable("Teams");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Title", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<bool>("Archived")
						.HasColumnType("bit");

					b.Property<string>("Description")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Titles");

					b.HasData(
						new
						{
							Id = 1,
							Archived = false,
							Description = "Active Project Manager",
							Name = "Project Manager"
						},
						new
						{
							Id = 2,
							Archived = false,
							Description = "Designer with Advanced sets of knowledge",
							Name = "Senior Designer"
						},
						new
						{
							Id = 3,
							Archived = false,
							Description = "A skilled graphic designer",
							Name = "Junior Designer"
						});
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
				{
					b.Property<string>("Id")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ConcurrencyStamp")
						.IsConcurrencyToken()
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Name")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.Property<string>("NormalizedName")
						.HasMaxLength(256)
						.HasColumnType("nvarchar(256)");

					b.HasKey("Id");

					b.HasIndex("NormalizedName")
						.IsUnique()
						.HasDatabaseName("RoleNameIndex")
						.HasFilter("[NormalizedName] IS NOT NULL");

					b.ToTable("AspNetRoles", (string)null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("RoleId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("RoleId");

					b.ToTable("AspNetRoleClaims", (string)null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("ClaimType")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("ClaimValue")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("Id");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserClaims", (string)null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderKey")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("ProviderDisplayName")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("UserId")
						.IsRequired()
						.HasColumnType("nvarchar(450)");

					b.HasKey("LoginProvider", "ProviderKey");

					b.HasIndex("UserId");

					b.ToTable("AspNetUserLogins", (string)null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("RoleId")
						.HasColumnType("nvarchar(450)");

					b.HasKey("UserId", "RoleId");

					b.HasIndex("RoleId");

					b.ToTable("AspNetUserRoles", (string)null);
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.Property<string>("UserId")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("LoginProvider")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Name")
						.HasColumnType("nvarchar(450)");

					b.Property<string>("Value")
						.HasColumnType("nvarchar(max)");

					b.HasKey("UserId", "LoginProvider", "Name");

					b.ToTable("AspNetUserTokens", (string)null);
				});

			modelBuilder.Entity("AppUserProject", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Project", null)
						.WithMany()
						.HasForeignKey("ProjectsId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UsersId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("AppUserTeam", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Team", null)
						.WithMany()
						.HasForeignKey("TeamsId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UsersId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.AppUser", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Group", "Group")
						.WithMany()
						.HasForeignKey("GroupId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.Title", "Title")
						.WithMany()
						.HasForeignKey("TitleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Group");

					b.Navigation("Title");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.LearningObjective", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Project", "Project")
						.WithMany("LearningObjectives")
						.HasForeignKey("ProjectId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.LearningObjectiveType", "Type")
						.WithMany()
						.HasForeignKey("TypeId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Project");

					b.Navigation("Type");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Schema", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Group", "Group")
						.WithMany()
						.HasForeignKey("GroupId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.LearningObjectiveType", "Type")
						.WithMany()
						.HasForeignKey("TypeId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Group");

					b.Navigation("Type");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Task", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Group", "Group")
						.WithMany()
						.HasForeignKey("GroupId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.LearningObjective", "LearningObjective")
						.WithMany()
						.HasForeignKey("LearningObjectiveId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.Task", "Parent")
						.WithMany()
						.HasForeignKey("ParentId");

					b.HasOne("AutomatedTaskSystem.Models.Project", "Project")
						.WithMany()
						.HasForeignKey("ProjectId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.Schema", "Schema")
						.WithMany()
						.HasForeignKey("SchemaId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.TaskStatus", "Status")
						.WithMany()
						.HasForeignKey("StatusId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.AppUser", "User")
						.WithMany()
						.HasForeignKey("UserId");

					b.Navigation("Group");

					b.Navigation("LearningObjective");

					b.Navigation("Parent");

					b.Navigation("Project");

					b.Navigation("Schema");

					b.Navigation("Status");

					b.Navigation("User");
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Team", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.Group", "Group")
						.WithMany()
						.HasForeignKey("GroupId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Group");
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
				{
					b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
				{
					b.HasOne("AutomatedTaskSystem.Models.AppUser", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("AutomatedTaskSystem.Models.Project", b =>
				{
					b.Navigation("LearningObjectives");
				});
#pragma warning restore 612, 618
		}
	}
}
